# Generated by Django 3.2.7 on 2022-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20220617_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='href',
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
