# Generated by Django 3.2.7 on 2022-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=True),
        ),
    ]
