# Generated by Django 3.2.7 on 2022-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_voter_voted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('wins', models.IntegerField(default=1)),
                ('votes', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='href',
            field=models.CharField(default='', max_length=200),
        ),
    ]
