# Generated by Django 3.2.7 on 2022-08-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20220822_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
