# Generated by Django 3.2.7 on 2022-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20220823_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.TextField(default='Hey there, this is my profile on Movie-Contest.live'),
        ),
    ]
