# Generated by Django 3.2.7 on 2022-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_details_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='favourite_movie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='favourite_series',
            field=models.CharField(default='', max_length=200),
        ),
    ]
