# Generated by Django 3.2.7 on 2022-08-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20220823_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='social',
            field=models.CharField(default='', max_length=400),
        ),
    ]
