# Generated by Django 3.2.7 on 2022-10-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_set_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.set'),
        ),
    ]
